/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      colors: {
        sage: {
          primary:              '#4F6354',
          'on-primary':         '#FFFFFF',
          'primary-container':  '#D2E8D6',
          'on-primary-container': '#0C1F13',
          secondary:            '#536254',
          'on-secondary':       '#FFFFFF',
          'secondary-container':'#D6E7D5',
          'on-secondary-container': '#59685A',
          tertiary:             '#244C5A',
          'on-tertiary':        '#FFFFFF',
          'tertiary-container': '#3D6473',
          'on-tertiary-container': '#B7DFF1',
          bg:                   '#FAFDF7',
          surface:              '#FFFFFF',
          'surface-low':        '#F4F7F1',
          'surface-med':        '#EEF2EC',
          'surface-high':       '#E8EDE6',
          'surface-highest':    '#E2E7E0',
          'on-surface':         '#1A1C1A',
          'on-surface-var':     '#5F635E',
          outline:              '#737971',
          'outline-var':        '#C2C8BF',
          error:                '#BA1A1A',
          'error-container':    '#FFDAD6',
          'on-error-container': '#93000A',
          success:              '#2E7D32',
          'success-container':  '#C8E6C9',
          warning:              '#B7791F',
          'warning-container':  '#FEF3C7',
          inverse:              '#2C322B',
          'inverse-surface':    '#EDF2E9',
        },
      },
      borderRadius: {
        sm:   '0.5rem',
        DEFAULT: '1rem',
        md:   '1.5rem',
        lg:   '2rem',
        xl:   '3rem',
        full: '9999px',
      },
      boxShadow: {
        level1: '0px 1px 3px 1px rgba(26,28,26,0.05), 0px 1px 2px 0px rgba(26,28,26,0.08)',
        level2: '0px 2px 6px 2px rgba(26,28,26,0.06), 0px 1px 2px 0px rgba(26,28,26,0.08)',
        level3: '0px 4px 8px 3px rgba(26,28,26,0.08), 0px 1px 3px 0px rgba(26,28,26,0.12)',
      },
      fontSize: {
        'display': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600', letterSpacing: '0.15px' }],
        'title-sm': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.1px' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.4px' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.1px' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.5px' }],
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.5px' }],
      },
    },
  },
  plugins: [],
}
